iiips/urls.py
from django.contrib import admin
from django.urls import path
from proyectos import views
from django.conf import settings
from django.contrib.staticfiles.urls import static
from proyectos.views import UserListView
from proyectos.views import UserDeletedListView
from proyectos.views import editarusuario

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #usuarios
    #path('dashboard/',views.dashboard, name='dashboard'),
    path('listarusuarios', UserListView.as_view(), name='listarusuarios'),
    path('listarusuarioseliminado/', UserDeletedListView.as_view(), name='listarusuarioseliminado'),
    path('listarusuarioseliminado/<int:user_id>/', views.eliminar_usuario, name='eliminar_usuario'),
    path('editarusuario/<int:user_id>/', views.editarusuario, name='editarusuario'),
    path('registrarusuario/', views.registrarusuario, name='registrarusuario'),
    path('permisos_insuficientes/',views.permisos_insuficientes, name='permisos_insuficientes'),
    #path('reactivar_usuario/<int:user_id>/', views.reactivar_usuario, name='reactivar_usuario'),
    path('usuario/reactivar/<int:user_id>/', views.reactivar_usuario, name='reactivar_usuario'),
    
    
    
    path('', views.home, name='home'),
    path('registrar/', views.registrar, name='registrar'),
    path('logout/',views.signout, name='logout'),
    path('signin/',views.signin, name='signin'),
    
    path('index', views.index, name='index'),
    path('materias/<int:ids>', views.materias, name='materias'),
    path('VerSemestres', views.VerSemestres, name='VerSemestres'),
    
    
   # path('formuno', views.formuno, name='formuno'),
    path('vista/<int:Id_M>', views.vista, name='vista'),
    path('vistas', views.vistas, name='vistas'),
    #proyeto
    path('semestres/crear',views.crear,name='crear'),
    path('semestres/editar/<int:id>',views.editar,name='editar'),
    path('form',views.form,name='form'),
    path('proye',views.proye, name='proye'),
    path('eliminar/<int:id>',views.eliminar,name='eliminar'),
    
    #fases o estapas
    path('FaseEtapa/crearf',views.crearf,name='crearf'),
    path('FaseEtapa/editarf<int:idf>',views.editarf,name='editarf'),
    path('FaseEtapa/formf',views.form,name='formf'),
    path('etapa',views.etapa, name='etapa'),
    path('eliminarf/<int:idf>',views.eliminarf,name='eliminarf'),
    
    #cursos proyecto
    path('curso/crearc',views.crearc,name='crearc'),
    path('curso/editarc/<int:idm>',views.editarc ,name='editarc'),
    path('curso/formc',views.formc,name='formc'),
    path('curso',views.curso, name='curso'),
    path('eliminarm/<int:idm>',views.eliminarm,name='eliminarm'),
    
    #Gestion proyecto
    path('Gestion/crearg',views.crearg,name='crearg'),
    path('Gestion/editarg/<int:idg>',views.editarg ,name='editarg'),
    path('Gestion/formg',views.formg,name='formg'),
    path('gest',views.gest, name='gest'),
    path('eliminarg/<int:idg>',views.eliminarg,name='eliminarg'),
    
    #Semestre proyecto
    path('materia/crearm',views.crears, name='crears'),
    path('materia/editarm/<int:ids>',views.editars, name='editars'),
    path('materia/formm',views.forms, name='forms'),
    path('semest',views.semest, name='semest'),
    path('eliminars/<int:ids>', views.eliminars, name='eliminars'),
    
    #tipo proyecto
    path('Tipo/creart',views.creart, name='creart'),
    path('Tipo/editart/<int:idt>',views.editart, name='editart'),
    path('Tipo/formt',views.formt, name='formt'),
    path('tippo',views.tippo, name='tippo'),
    path('eliminart/<int:idt>', views.eliminart, name='eliminart'),
    
    
    
    path('materiaforn', views.materiaform, name='materiaform'),
    
    
    #paralelos con sus materias
    path('unoA', views.unoA, name='unoA'),
    path('unoB', views.unoB, name='unoB'),
    path('dosA', views.dosA, name='dosA'),
    path('dosB', views.dosB, name='dosB'),
    path('tresA', views.tresA, name='tresA'),
    path('tresB', views.tresB, name='tresB'),
    path('cuatroA', views.cuatroA, name='cuatroA'),
    path('cuatroB', views.cuatroB, name='cuatroB'),
    path('quinto', views.quinto, name='quinto'),
    path('sexto', views.sexto, name='sexto'),
    path('septimo', views.septimo, name='septimo'),
    path('octavo', views.octavo, name='octavo'),
    path('octavoR', views.octavoR, name='octavoR'),
    path('noveno', views.noveno, name='noveno'),
    path('novenoR', views.novenoR, name='novenoR'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyectos/forms.py
from django import forms
from .models import T_Proyectos
from .models import T_Fase_proyecto
from .models import T_Gestion
from .models import T_Materia
from .models import T_Semestre
from .models import T_Tipo_Proyecto
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class PForm(forms.ModelForm):
    class Meta:
        model = T_Proyectos
        fields = ['Titulo','Fecha_Inicio','Fecha_Finalizacion','Descripcion','Documentacion','Imagen','T_Fase_proyecto','T_Gestion',
                   'T_Tipo_Proyecto','T_Materia']
      
    Fecha_Inicio = forms.DateField(widget=forms.DateInput(attrs={'type':'date'}))
    Fecha_Finalizacion = forms.DateField(widget=forms.DateInput(attrs={'type':'date'}))
    Descripcion = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Ingrese la Descripcion'}))
    
    
    
# 'descripcion_Problema': forms.Textarea(attrs={'class': 'form-control', 'placeholder':'Ingrese la Descripcion' }),
    # ['Titulo','Fecha_Inicio','Fecha_Finalizacion','Descripcion','Documentacion','Imagen','T_Fase_proyecto','T_Gestion',
             #      'T_Tipo_Proyecto','T_Materia']

class FForm(forms.ModelForm):
    class Meta:
        model = T_Fase_proyecto
        fields = '__all__'
        
class GForm(forms.ModelForm):
    class Meta:
        model = T_Gestion
        fields = '__all__'

class MForm(forms.ModelForm):
    class Meta:
        model = T_Materia
        
        fields = '__all__'
    


class SForm(forms.ModelForm):
    class Meta:
        model = T_Semestre
        fields = '__all__'
        
class TForm(forms.ModelForm):
    class Meta:
        model = T_Tipo_Proyecto
        fields = '__all__'
        
        
#permisos usuarios
class SuperuserPermissionForm(UserChangeForm):
    class Meta:
        model = User
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Agrega cualquier personalización adicional aquí si es necesario
        
class RegistrationForm(UserCreationForm):
    # Agrega campos adicionales si es necesario
    is_superuser = forms.BooleanField(required=False)
    is_staff = forms.BooleanField(required=False)
    is_active = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'is_superuser', 'is_staff', 'is_active')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_superuser = self.cleaned_data['is_superuser']
        user.is_staff = self.cleaned_data['is_staff']
        user.is_active = self.cleaned_data['is_active']
        if commit:
            user.save()
        return user

proyectos/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from .import models 
from .forms import PForm, FForm, TForm, MForm, SForm, GForm
from django.contrib.auth.decorators import permission_required

from django.contrib import admin
from django.contrib.auth.admin import UserAdmin

from .forms import SuperuserPermissionForm


from django.views.generic import ListView

from django.contrib.auth.forms import UserChangeForm
from .forms import RegistrationForm
from django.contrib import messages  # Importe a biblioteca de mensagens
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Permission

from django.core.paginator import Paginator
# Create your views here.

class UserListView(ListView):
    model = User
    template_name = 'listarusuarios.html'
    context_object_name = 'users'

    def get_queryset(self):
        # Filtrar solo usuarios activos
        return User.objects.filter(is_active=True)

class UserDeletedListView(ListView):
    model = User
    template_name = 'listarusuarioseliminado.html'  # Nombre de la plantilla HTML para la lista de usuarios eliminados
    context_object_name = 'deleted_users'  # Nombre del objeto que representará la lista de usuarios eliminados en la plantilla
    queryset = User.objects.filter(is_active=False)  # Consulta para recuperar usuarios eliminados
    
class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'is_superuser', 'is_staff', 'is_active']

def check_permissions(user):
    return user.is_superuser or user.is_staff

def permisos_insuficientes(request):
    return render(request, 'permisos_insuficientes.html')

@user_passes_test(check_permissions, login_url='/permisos_insuficientes/')
def dashboard(request):
    context = {'usuario_actual': request.user}
    return render(request, 'dashboard.html',context)

@login_required
def eliminar_usuario(request, user_id):
    user = get_object_or_404(User, id=user_id)
    user.is_active = False  # Marcar el usuario como inactivo
    user.save()  # Guardar el cambio
    messages.success(request, 'Usuario desactivado exitosamente.')
    return redirect('listarusuarios')  # Redirigir a la lista de usuarios o a donde desees
        
@permission_required('permiso_especifico')   
def editarusuario(request, user_id):
    usuario = get_object_or_404(User, id=user_id)
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=usuario)
        if form.is_valid():
            form.save()
            # Obtener los IDs de permisos seleccionados del formulario
            selected_perm_ids = request.POST.getlist('permissions')
            # Limpiar los permisos actuales
            usuario.user_permissions.clear()
            # Asignar los nuevos permisos al usuario
            for perm_id in selected_perm_ids:
                perm = Permission.objects.get(id=perm_id)
                usuario.user_permissions.add(perm)
            usuario.save()
            return redirect('listarusuarios')
    else:
        form = CustomUserChangeForm(instance=usuario)
    # Obtener todos los permisos y los permisos actuales del usuario
    all_perms = Permission.objects.all()
    user_perms = usuario.user_permissions.all()
    return render(request, 'editarusuario.html', {
        'form': form,
        'user': usuario,
        'all_perms': all_perms,
        'user_perms': user_perms
    })
    
@login_required
def registrarusuario(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.is_superuser = form.cleaned_data.get('is_superuser')
            user.is_staff = form.cleaned_data.get('is_staff')
            user.is_active = form.cleaned_data.get('is_active')
            user.save()
            messages.success(request, 'Usuario registrado exitosamente.')
            return redirect('listarusuarios')

    else:
        form = RegistrationForm()

    return render(request, 'registrarusuario.html', {'form': form})

@login_required
def reactivar_usuario(request, user_id):
    user = get_object_or_404(User, id=user_id)
    user.is_active = True
    user.save()
    # Redirige a la vista que muestra la lista de usuarios eliminados
    return redirect('listarusuarioseliminado')

# def editarusuario(request, usuario_id):
#     # Obtén el usuario que deseas editar
#     usuario = User.objects.get(id=usuario_id)

#     # Verifica si la solicitud es un POST (es decir, si se envió el formulario)
#     if request.method == 'POST':
#         # Crea una instancia del formulario con los datos de la solicitud
#         form = SuperuserPermissionForm(request.POST, instance=usuario)
#         # Guarda los cambios si el formulario es válido
#         if form.is_valid():
#             form.save()
#     else:
#         # Si no es un POST, crea una instancia del formulario con los datos actuales del usuario
#         form = SuperuserPermissionForm(instance=usuario)

#     return render(request, 'formuser.html', {'form': form, 'usuario': usuario})

class CustomUserAdmin(UserAdmin):
    form = SuperuserPermissionForm

admin.site.unregister(User)
admin.site.register(User, CustomUserAdmin)

# Create your views here.


def home(request):
    return render(request, 'home.html')

@login_required
def registrar(request):
    if request.method == 'GET':
        return render(request, 'registrar.html', {
            'form': UserCreationForm
        })
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(
                    username=request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('home')
            except IntegrityError:
                return render(request, 'registrar.html', {
                    'form': UserCreationForm,
                    "error": 'User ya existe'
                })
        return render(request, 'registrar.html', {
            'form': UserCreationForm,
            "error": 'la contraseña no concide'
        })


def signout(request):
    logout(request)
    return redirect('home')


def signin(request):
    if request.method == 'GET':
        return render(request, 'signin.html', {
            'form': AuthenticationForm
        })
    else:
        user = authenticate(
            request, username=request.POST['username'], password=request.POST
            ['password'])
        if user is None:
            return render(request, 'signin.html', {
                'form': AuthenticationForm,
                'error': 'Usuario y contraseña incorrecta'
            })
        else:
            login(request, user)
            return redirect('home')
       
def index(request):
    Id_Materia=models.T_Materia.objects.get(pk=3)
    return render(request, 'semestres/index.html',{
        'Id_Materia' : Id_Materia
    })

def formuno(request):
    return render(request, 'unesemestres/formuno.html')

#def vista(request, Id_M):
   # Id_Materia=models.T_Materia.objects.get(pk=Id_M)
   # datos=models.T_Proyectos.objects.filter(T_Materia=Id_Materia)
  #  return render(request, 'semestres/vista.html',{'datos': datos,})

def vista(request, Id_M):
    Id_Materia=models.T_Materia.objects.get(pk=Id_M)
    datos=models.T_Proyectos.objects.filter(T_Materia=Id_Materia)
    paginator = Paginator(datos,1)
    page_number = request.GET.get('page')  # Obtén el número de página de la URL
    datos = paginator.get_page(page_number)  # Obtiene la página actual
    
    return render(request, 'semestres/vista.html',{'datos': datos,})


def vistas(request):
    semestres = models.T_Semestre.objects.all()
    
    return render(request, 'semestres/vistas.html',{
        'semestres': semestres,
    })

def materias(request,ids):
    semestre = models.T_Semestre.objects.get(Id_Semestre= ids)
    materiasSemestre= models.T_Materia.objects.filter(T_Semestre=semestre)
    return render(request, 'paralelos/materias.html',{
        'semestre': semestre,
        'materias':materiasSemestre,   
    })
    
@login_required  
def VerSemestres(request):
    return render(request, 'paralelos/VerSemestres.html')


# poryectos
@login_required
def crear(request):
    formulario = PForm(request.POST or None, request.FILES or None)
    if formulario.is_valid():
        formulario.save()
        return redirect('proye')
    return render(request, 'semestres/crear.html',{'formulario': formulario})


# mform = models.T_Materia.objects.get(Id_Materia=idm)
#     formularioc = MForm(request.POST or None, request.FILES or None, instance=mform)
#     # formularioc = MForm()
#     if formularioc.is_valid() and request.POST:
#         formularioc.save()
#         return redirect('proye')
#     #return render(request,'curso/editarc.html')
#     return render(request, 'curso/editarc.html',{'formularioc': formularioc})
@login_required
def editar(request, id):
    programa = models.T_Proyectos.objects.get(Id_Proyect=id)
    formulario = PForm(request.POST or None, request.FILES or None, instance=programa)
    if formulario.is_valid() and request.POST:
        formulario.save()
        return redirect('proye')
    return render(request, 'semestres/editar.html',{'formulario': formulario})
@login_required
def form(request):
    return render(request, 'semestres/form.html')
@login_required
def proye(request):
     programa = models.T_Proyectos.objects.all()
     return render(request, 'semestres/indexgeneral.html',{'programa': programa})
@login_required 

proyectos/templates/permisosUser/editarusuarios.html
{% extends 'p_principal.html' %}

{% block content %}
  <h2>Editar Usuario: {{ usuario.username }}</h2>
  <form method="post" action="{% url 'editarusuario' usuario.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar cambios</button>
  </form>
{% endblock %}

proyectos/templates/permisosUser/permisos_insuficientes.html
{% extends "base.html" %}

{% block content %}
{% if user.is_superuser or user.is_staff %}

{% else %}
<main class="container justify-content-center align-items-center ">
    <div class="row d-flex justify-content-center ">
        <div class="col-12 col-md-8 col-lg-6 ">
            <div class="card bg-white mt-5">
                <div class="card-body p-5  mt-5">
                    <h1>No tienes permisos para acceder a esta página.</h1>
                    <div class="d-flex justify-content-center">
                        <button type="button" class="btn btn-danger" onclick="window.location.href='{% url 'home' %}'">Volver</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endif %}

{% endblock %}

proyectos/templates/permisosUser/registrarse.html
{% extends "base.html" %}

{% block content %}
        <main class="container justify-content-center align-items-center ">
          <div class="row d-flex justify-content-center ">
            <div class="col-12 col-md-8 col-lg-6 ">
              <div class="card bg-white mt-5">
                <div class="card-body p-5 mt-5">
                  <form action="/registrarse/" method="POST" class=" mb-3 mt-md-4">
                    {% csrf_token %}
                    {{error}}
                    <h2 class=" fw-bold mb-2 text-uppercase ">Registrarse</h2>
                    <p class=" mb-4">Ingrese su cuenta!</p>
                    
                    <div class=" row mb-3">
                      <label for="email" class="form-label ">Correo Electronico</label>
                      <input type="email" class="form-control" name="username" id="username" placeholder="name@example.com">
                    </div>
                    <div class=" row mb-3">
                      <label for="password" class="form-label ">Contraseña</label>
                      <input type="password" class="form-control" name="password1" id="password1" placeholder="*******">
                    </div>
                    <div class=" row mb-3">
                      <label for="password" class="form-label ">confirmar Contraseña</label>
                      <input type="password" class= "form-control" name= "password2" id= "password2" placeholder = "*******">
                    </div>
                    
                    <div class="d-grid">
                      <button class="btn btn-outline-dark" type="submit">Registrar</button>
                    </div>
                  </form>
                  <div>
                    <p class="mb-0 text-center">¿Ya estás registrado? <a href="{% url 'ingresar' %}" class="text-primary fw-bold">Ingresar.!</a></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </main>

{% endblock %}

proyectos/templates/permisosUser/registrarusuario.html
{% extends "base_dashboard.html" %}

{% load static %}

{%block content%}
            <main class="container justify-content-center align-items-center">
                <div class="row d-flex justify-content-center">
                    <div class="col-12 col-md-8 col-lg-6">
                        <div class="card bg-white mt-5">
                            <div class="card-body p-5 mt-5">
                                <h1>Registrar Usuario</h1>
                                <form method="post" action="{% url 'registrarusuario' %}" class=" mb-3 mt-md-4">
                                    {% csrf_token %}
                                    
                                    <div class="form-group">
                                        {{ form.username.label_tag }}
                                        {{ form.username }}
                                        <span class="text-danger">{{ form.username.errors }}</span>
                                    </div>
                                    
                                    <div class="form-group">
                                        {{ form.first_name.label_tag }}
                                        {{ form.first_name }}
                                        <span class="text-danger">{{ form.first_name.errors }}</span>
                                    </div>
                                    
                                    <div class="form-group">
                                        {{ form.last_name.label_tag }}
                                        {{ form.last_name }}
                                        <span class="text-danger">{{ form.last_name.errors }}</span>
                                    </div>
                                    
                                    <div class="form-group">
                                        {{ form.email.label_tag }}
                                        {{ form.email }}
                                        <span class="text-danger">{{ form.email.errors }}</span>
                                    </div>
                                    
                                    <div class="form-group">
                                        {{ form.password1.label_tag }}
                                        {{ form.password1 }}
                                        <span class="text-danger">{{ form.password1.errors }}</span>
                                    </div>
                                    
                                    <div class="form-group">
                                        {{ form.password2.label_tag }}
                                        {{ form.password2 }}
                                        <span class="text-danger">{{ form.password2.errors }}</span>
                                    </div>
                                    <div class="form-check">
                                        {{ form.is_superuser }}
                                        <label for="id_is_superuser" class="form-check-label">¿Es superusuario? Marque para otorgar privilegios de superusuario.</label>
                                    </div>
                                    
                                    <div class="form-check">
                                        {{ form.is_staff }}
                                        <label for="id_is_staff" class="form-check-label">¿Es staff? Marque para otorgar privilegios de staff.</label>
                                    </div>
                                    
                                    <div class="form-check">
                                        {{ form.is_active }}
                                        <label for="id_is_active" class="form-check-label">¿Está activo? Marque para activar al usuario.</label>
                                    </div>
                                    
                                    <button type="submit" class="btn btn-primary">Registrar Usuario</button>
                                    <button type="button" class="btn btn-danger" onclick="window.location.href='{% url 'dashboard' %}'">Volver</button>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
{% endblock %}